/* Alumno:Eduardo Missael Torres LOPEZ
Matricula: #1895450 */
console.log("Hola javascrip");
console.warn("Hola a todos")
console.error("Saludos")

console.log(`El tipo de dato 
    de false ${typeof false} `);

console.log(`El tipo de dato 
    de 5.5 ${typeof 5.5} `);
console.log(`El tipo de dato 
    de js ${typeof 'js'} `);

console.log(`El resultado de: 
        ${ !3 > 1 || 3 == 2 }`);

console.log( 3 > 2 ? "verdadero" : "falso");

const UNI = "UANL";

UNI = "PATITO";